# Generated by Django 4.0.4 on 2022-11-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_car_model_alter_user_f_name_alter_user_l_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_country',
            field=models.CharField(max_length=10),
        ),
    ]
